stages:
    - build
    - badge

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/runtime:3.1
  script:
    - echo "Testing the Batch file by Downloading a song."
    - "ls -al"
    - "./yt.bat"
    - "1"
    - "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  artifacts:
    paths:
      - Rick Astley - Never Gonna Give You Up (Video)

create_badge_svg:
  stage: badge
  image: python:3.6.6
  script:
    - echo "Python other dependencies installation"
  after_script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
        - commits.svg
    when: always
    expire_in: 16 weeks